# Generated by Django 4.2.10 on 2024-03-06 02:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='note',
            name='content',
            field=models.TextField(max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='note',
            name='key',
            field=models.TextField(max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='note',
            name='summary',
            field=models.TextField(max_length=1000, null=True),
        ),
    ]
