# Generated by Django 4.2.10 on 2024-03-06 17:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0002_alter_note_content_alter_note_key_alter_note_summary'),
    ]

    operations = [
        migrations.AddField(
            model_name='theme',
            name='font',
            field=models.CharField(default='1', max_length=1),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='note',
            name='content',
            field=models.TextField(blank=True, default='', max_length=1000),
        ),
        migrations.AlterField(
            model_name='note',
            name='key',
            field=models.TextField(blank=True, default='', max_length=1000),
        ),
        migrations.AlterField(
            model_name='note',
            name='summary',
            field=models.TextField(blank=True, default='', max_length=1000),
        ),
    ]
