# Generated by Django 4.2.11 on 2024-03-07 19:53

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0003_theme_font_alter_note_content_alter_note_key_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='note',
            name='content',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='note',
            name='date',
            field=models.DateField(default=datetime.datetime.now, verbose_name='Class Date'),
        ),
        migrations.AlterField(
            model_name='note',
            name='key',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='note',
            name='summary',
            field=models.TextField(blank=True, default=''),
        ),
    ]
